### ISSUE TITLE
Compatibility with "reorder workspaces" is broken

### ISSUE THREAD

**Issue by Morikko** [christopher-l/space-bar#16]
:wave:  This extension https://github.com/smmr0/gnome-reorder-workspaces allows to swap a workspace to the left or right with a shortcut `Ctrl + Super + Up/Down`.

Before the last release, it used to work and the workspace name was swapped as well. Now, the workspace is swapped but the names stay in the old position.

As a side note, reorder with a keyboard shortcut may be a nice feature to make space-bar more self sufficient. As for now reordering is bound to the mouse only.

**Comment by christopher-l** [comment]
I think the reason is, that the release included behavior that notices workspace changes done by other extensions and adapts workspace names while the reorder-workspaces extensions reorders workspace names itself. So both extensions cancel each other out now.

Not sure what is the best solution to this. Would providing keyboard shortcuts solve the issue for you?

**Comment by christopher-l** [comment]
It seems the maintainer of the reorder-workspace extension was nice enough to provide a fix with their extension: https://github.com/christopher-l/space-bar/commit/bbc7b07479360cb46647befcad6de8497ebdb33f#commitcomment-122700347

**Comment by Morikko** [comment]
Oh wow it was fast. I did not know workspace names was a "Gnome" feature, I thought it was purely a Space Bar thing. That's why I open the issue here. Now, your previous message is more clear for me.

You built a great extension :+1:
