### ISSUE TITLE
Feature Request, individual backgrounds for workspaces

### ISSUE THREAD

**Issue by juergmaier** [christopher-l/space-bar#25]
Love the extension to give me back workspace selection by name with newer gnome version.
Would love to get an option to define a different background image for each workspace.

**Comment by christopher-l** [comment]
Hi @juergmaier, I'm glad you like the extension. :)

I see how different background images for each workspace would be useful, but currently, I wouldn't consider this to be in the scope of this extension. Since this feature would be interesting independently of the functionality of this extension, a separate extension might be a good idea.
