### ISSUE TITLE
Feature Request: Display workspace names on overview

### ISSUE THREAD

**Issue by uacode** [christopher-l/space-bar#32]
Hello, thanks for this Gnome extension. I have this idea :)

https://imgur.com/FAeNBg1.png

**Comment by christopher-l** [comment]
Hey @uacode,
Thanks for your suggestion. I can see how this could be useful. However—or luckily—since the workspace names used by this extension are a standard GNOME feature, this can be implemented completely independently of this extension. So I think a separate extension for this would be a better option since this feature could also be useful without using Space Bar.

As a side note, there is also the option to primarily use Space Bar's workspace indicator in the overview. It supports drag-and-dropping windows onto workspace labels and the standard workspace mini views can be hidden with an extension like Just Perfection.
