### ISSUE TITLE
Renaming is not persistent

### ISSUE THREAD

**Issue by Maxga** [christopher-l/space-bar#44]
Hi,
I'm on Gnome46 and it seems like the renaming of workspaces is not persistent.
I was able to change the name of workspace 1 to something of my choice.

However, if I then switch to workspace 2 and rename it, the new name is shown, but upon switching back to workspace 1, the name is then set back to "2".

**Comment by christopher-l** [comment]
Hi @Maxga!

Maybe you have enabled "Smart Workspace Names" in the extensions "Behavior" settings? In that case, this might be intended behavior.

Otherwise, I don't know what could cause the issue. You could try monitoring the saved names using dconf-editor:

```sh
dconf-editor /org/gnome/desktop/wm/preferences/workspace-names
```

You could also try watching the logs for gnome-shell and see if anything comes up:

```sh
journalctl -f -o cat /usr/bin/gnome-shell
```

**Comment by Maxga** [comment]
Hi @christopher-l ,
I just did a fresh install of gnome, and now I dont face the problem anymore.
I was switching from KDE to Gnome before, so I guess some residues created this issue. Or some font stuff, where it couldnt handle some fonts correctly? Hard to tell, anyways, cant reproduce anymore, thanks.
